services:
  books-db:
    image: postgres:17
    container_name: book-db
    ports:
      - "2025:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: books
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    restart: unless-stopped